apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dir-rwx-example
  labels:
    app: cache-dir-rwx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-dir-rwx-example
  template:
    metadata:
      labels:
        app: cache-dir-rwx-example
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: cache-dir-rwx-example
      containers:
      - name: pause
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - 'hostname >> /data/shared.txt; sleep 3; cat /data/shared.txt; sleep infinity'
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: cache-dir-rwx-example
